apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-defaults
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - plugin:
        # Specify the configMap where the plugin configuration is located.
        configMapRef:
          name: namespace-generator-plugin
        # You can pass arbitrary parameters to the plugin. `input.parameters` is a map, but values may be any type.
        # These parameters will also be available on the generator's output under the `generator.input.parameters` key.
        input:
          parameters:
            labelSelector:
              matchLabels:
                konflux.ci/type: user
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: DoesNotExist

        # When using a Plugin generator, the ApplicationSet controller polls every `requeueAfterSeconds` interval (defaulting to every 30 minutes) to detect changes.
        requeueAfterSeconds: 1
  template:
    metadata:
      name: "{{ .namespace }}-default-app"
