---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-generator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-generator-namespace-lister
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-generator-namespace-lister
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-generator-namespace-lister
subjects:
- kind: ServiceAccount
  name: namespace-generator
  # todo set the namespace with kustomize
  namespace: argocd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: namespace-generator
  name: namespace-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: namespace-generator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: namespace-generator
    spec:
      serviceAccountName: namespace-generator
      containers:
      - image: quay.io/gbenhaim0/namespace-generator:v10
        env:
          - name: NS_GEN_USE_HTTP
            value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        volumeMounts:
        - mountPath: /mnt/serving-certs
          name: cert
          readOnly: true
        - mountPath: /mnt
          name: key
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: serving-certs
          optional: true
      - name: key
        secret:
          defaultMode: 420
          secretName: namespace-generator-key
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: serving-certs
  labels:
    app.kubernetes.io/part-of: namespace-generator
  name: namespace-generator
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    control-plane: namespace-generator
