apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: namespace-generator
  name: namespace-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: namespace-generator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: namespace-generator
    spec:
      serviceAccountName: namespace-generator
      containers:
      - image: quay.io/brianksmith/namespace-generator:latest
        env:
          - name: NS_GEN_USE_HTTP
            value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        volumeMounts:
        - mountPath: /mnt/serving-certs
          name: cert
          readOnly: true
        - mountPath: /mnt
          name: key
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: serving-certs
          optional: true
      - name: key
        secret:
          defaultMode: 420
          secretName: namespace-generator-key