apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cm.yaml
  - deployment.yaml
  - iam-member-policy.yaml
  - rbac.yaml
  - secret.yaml
  - service.yaml
  - serviceacocunt.yaml
namespace: argocd
