apiVersion: v1
kind: Secret
metadata:
  name: namespace-generator-key
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  key: 113de810f8a5b1efd06dd84139da5fa7c5d68aac
