apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: serving-certs
  labels:
    app.kubernetes.io/part-of: namespace-generator
  name: namespace-generator
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    control-plane: namespace-generator