apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: namespace-generator-workload-identitynamespace
  namespace: infra
  annotations:
    cnrm.cloud.google.com/project-id: platform-287919
spec:
  member: serviceAccount:platform-287919.svc.id.goog[argocd/namespace-generator]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    kind: IAMServiceAccount
    external: projects/platform-287919/serviceAccounts/argocd-namespace-generator@platform-287919.iam.gserviceaccount.com